In [7]:
from pre_process import svo_to_mp4s
import os

raw_dir = './convnert_reference_frame/obj-vid-capture'
outdir = os.path.dirname(raw_dir) + '/mp4s'

fnames = os.listdir(raw_dir)
for fname in fnames:
    f_in = os.path.join(raw_dir, fname)
    basename = os.path.basename(f_in).split('.')[0]
    f_out = os.path.join(outdir, basename)
    svo_to_mp4s(f_in, f_out)

./convnert_reference_frame/obj-vid-capture/HD1080_SN3404_12-48-53.svo
Converting SVO... Use Ctrl-C to interrupt conversion.


OpenCV: FFMPEG: tag 0x3253344d/'M4S2' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
OpenCV: FFMPEG: tag 0x3253344d/'M4S2' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'


[==============================] 100.000000%
SVO end has been reached. Exiting now.
The video id is HD1080_SN3404_12
./convnert_reference_frame/obj-vid-capture/HD1080_SN3404_12-53-39.svo
Converting SVO... Use Ctrl-C to interrupt conversion.


OpenCV: FFMPEG: tag 0x3253344d/'M4S2' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
OpenCV: FFMPEG: tag 0x3253344d/'M4S2' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'


[==============================] 100.000000%
SVO end has been reached. Exiting now.
The video id is HD1080_SN3404_12


In [51]:
vid_points_transformed

[array([   80.155112  ,  -224.66717292, -1950.91746878]),
 array([  110.52655412,  -100.38775872, -1537.62749851]),
 array([   82.20042959,   -77.47948073, -1937.4349379 ]),
 array([   71.16021718,  -227.77337819, -1513.7381101 ]),
 array([   67.53088659,     8.57623569, -1896.74864961]),
 array([   80.80238921,  -188.13961528, -1487.58542082]),
 array([   85.66217438,    32.25422317, -1859.85945048]),
 array([   79.58277204,  -251.46716129, -1854.03800991]),
 array([   61.23510165,  -236.68219143, -1557.17177478]),
 array([   68.95296888,    45.23329351, -1995.1158987 ]),
 array([   66.36188355,  -262.85735611, -1624.62535187]),
 array([   94.1782814 ,   -79.88299127, -1945.04478936]),
 array([   94.64928785,   -81.8325763 , -1949.26632595]),
 array([  106.17749486,   -77.77202383, -1445.48915293]),
 array([  112.6353123 ,    37.44666629, -2020.25182738]),
 array([   77.65823771,  -285.7851679 , -1485.76776716]),
 array([   82.20547746,  -291.08577201, -1480.62614226]),
 array([  104.

In [2]:
# ndi point pairs are obtained from the screen shots
ndi_point_pairs = [([64.93, -206.51, -1941.51],[62.58, -66.7, -1553.78]), 
               ([68.01, -62.88, -1948.01], [61.74, -220.39, -1512.61]),
               ([66.52, 16.06, -1910.72], [61.80, -167.61, -1494.75]),
               ([66.01, 50.76, -1876.74], [68.44, -235.36, -1843.89]),
               ([65.99, -235.15, -1546.93], [65.86, 55.10, -2017.27]),
               
              ([102.98, -302.40, -1607.55],[106.97, -103.16, -1952.37]), 
               ([112.11, -99.02, -1952.54], [113.52, -93.98, -1442.56]),
               ([118.21, 34.94, -2037.26], [116.23, -330.72, -1467.38]),
               ([116.80, -329.56, -1463.60], [119.30, -328.34, -1988.06]),
               ([120.34, -328.36, -1987.97], [116.71, 19.16, -1455.13])]

# vid point pairs are obtained from dlc and leastereo
vid_point_pairs = [([201.39, -116.3, 727.0],[-213.7, 2.803, 700.71]), 
               ([183.3, 2.564, 641.01], [-235.38, -122.55, 747.23]),
               ([139.20, 62.64, 580.00], [-262.29, -84.99, 732.64]),
               ([102.50, 92.60, 582.39], [105.51, -137.69, 748.30]),
               ([-192.22, -135.80, 742.13], [236.29, 92.41, 553.37]),
               
              ([-123.79, -153.88, 758.00],[191.56, 7.82, 651.56]), 
               ([195.86, 6.53, 652.86], [-306.62, 18.60, 689.04]),
               ([263.77, 112.37, 591.41], [-261.12, -164.88, 788.89]),
               ([-265.86, -166.36, 796.00], [263.17, -174.65, 797.48]),
               ([267.31, -178.21, 810.04], [-195.27, 104.25, 624.26])]

In [11]:
good_inds = []
thres = 20
for i, (ndi_pair, vid_pair) in enumerate(zip(ndi_point_pairs, vid_point_pairs)):
#     print(np.array(ndi_pair)[1] - np.array(ndi_pair)[0])
    ndi_norm = np.linalg.norm(np.array(ndi_pair)[0] - np.array(ndi_pair)[1], ord = 2)
    vid_norm = np.linalg.norm(np.array(vid_pair)[0] - np.array(vid_pair)[1], ord = 2)
    diff = abs(ndi_norm - vid_norm)
    print(diff)
    if diff < thres:
        good_inds.append(i)

20.465475951849385
13.358146792192201
0.5502979812733884
4.163651656312027
31.794309867615652
28.233180935902737
6.081434205829055
51.507303201182594
4.629641450468398
63.20616906602277


In [4]:
good_inds

[1, 2, 3, 6, 8]

In [61]:
from scipy.spatial.transform import Rotation as R
import numpy as np

def get_translation(ndi_pairs, vid_pairs, rot_matrix):
    translations = []
    for ndi, vid in zip(np.array(ndi_pairs).reshape(-1, 3), np.array(vid_pairs).reshape(-1,3)):
        diff = ndi - rot_matrix @ vid
        translations.append(diff)
    translation_mean = np.array(translations).mean(axis=0)
    return translation_mean

def get_rotation(ndi_pairs, vid_pairs):
    ndi_vecs = np.array(ndi_pairs)[:,1,:] - np.array(ndi_pairs)[:,0,:]
    vid_vecs = np.array(vid_pairs)[:,1,:] - np.array(vid_pairs)[:,0,:]
#     print(ndi_vecs, 'nid_vecs')
#     print(vid_vecs, 'vid_vecs')
    r, e = R.align_vectors(ndi_vecs, vid_vecs)
    return r, e

nid_pairs_good = [ndi_point_pairs[i] for i in good_inds]
vid_pairs_good = [vid_point_pairs[i] for i in good_inds]

r, e = get_rotation(nid_pairs_good, vid_pairs_good)
rot_matrix = r.as_matrix()

t = get_translation(nid_pairs_good, vid_pairs_good, rot_matrix)

print(f'Translation is :{t}')
print(f'Rotation is: {rot_matrix}')

Translation is :[ -439.43387119   311.38679179 -1791.90156532]
Rotation is: [[ 0.04891916  0.60149851  0.79737473]
 [-0.03214019  0.7988651  -0.60065095]
 [-0.99828549  0.00375556  0.05841208]]


In [83]:
dists = []
for ndi, vid in zip(np.array(ndi_point_pairs).reshape(-1,3), np.array(vid_point_pairs).reshape(-1,3)):
    dist = np.linalg.norm(ndi - (rot_matrix @ vid + t))
    print(dist)
    dists.append(dist)
print(np.array(dists).mean())

25.494851105890174
60.78355405785736
22.942211488691854
12.021954818799228
15.881664007983948
28.87710328236232
31.837472985720968
22.05865178709771
11.395201605819041
24.448365135514745
56.533837475122205
27.55187672473963
24.71843328697723
18.033047722043566
18.07314180956948
62.008305601516135
54.46959453903129
28.525149058575707
25.521277793099063
105.33141926062505
33.82535567735184


In [66]:
from rigid_transform_3D import rigid_transform_3D

In [73]:
nid_pairs_good_train =  np.array(nid_pairs_good).reshape(-1, 3).T
vid_pairs_good_train =  np.array(vid_pairs_good).reshape(-1, 3).T

rot_matrix_2, t_2 = rigid_transform_3D(vid_pairs_good_train, nid_pairs_good_train)

In [88]:
dists_2 = []
for ndi, vid in zip(np.array(ndi_point_pairs).reshape(-1,3), np.array(vid_point_pairs).reshape(-1,3)):
    dist = np.linalg.norm(ndi - (rot_matrix_2 @ vid + t_2.flatten()))
    dists_2.append(dist)
print(np.array(dists_2).mean())

33.61105618318187
